---
# tasks file for base-config
 
- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

#- name: enable repos
#  template:
#    src: repos_template.j2
#    dest: /etc/yum.repos.d/open_three-tier-app.repo
#    mode: 0644

#- name: install base tools and packages
#  yum:
#    name: "{{ item }}" 
#    state: latest
#  loop:
#    - httpie
#    - python-pip
#
- name: create directory for rpm files
  file:
    path: /tmp/rpms
    state: directory
    owner: root
    mode: 0644

- name: copy rpms
  copy:
    src: "{{ item }}"
    dest: /tmp/rpms/
  loop: "{{ files2copy }}"

- name: install rpms
  yum:
    name: /tmp/rpms/{{ item }}
    state: present
  loop: "{{ files2copy }}"
